spring:
  application:
    name: mcp
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct
          temperature: 0
    mcp:
      client:
        stdio:
          connections:
            filesystem:
              command: "npx${WINDOW_NPX_FILE:}"
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "/"
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true