spring:
  application:
    name: mcp
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct
          temperature: 0
    mcp:
      client:
        stdio:
          connections:
            filesystem:
              command: "npx"
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "/"
